### ISSUE TITLE
How do you update the list?

### ISSUE THREAD

**Issue by reneklacan** [thisisu/hosts#1]
Hey, stumbled upon your repo and I was just curious that based on what criteria do you update your list?

**Comment by thisisu** [comment]
I use the sort.bat file when I have new domains and then the Build_Hosts_Solo.bat to apply the hosts file to my PC. All the domains should fall into a category I have listed in the readme.

**Comment by reneklacan** [comment]
Thank you for your answer.

I was more specifically asking about this part:

> when I have new domains 

So how do you actually get new domains?

**Comment by thisisu** [comment]
Tricks of the trade ;)

**Comment by reneklacan** [comment]
🤷‍♂
